language: java
jdk:
  - oraclejdk8
notifications:
  email: false
  irc:
    channels:
      - "irc.spi.gt#techcable"
before_install:
  - git config --global user.email "Techcable@outlook.com"
  - git config --global user.name "Travis CI"
  - ./prepare-build.sh
sudo: false
cache:
  directories:
    - '$HOME/.m2/repository'
    - 'work/nms-src'
